apiVersion: v1
kind: Service
metadata:
  name: samba-ad
  labels:
    app.kubernetes.io/name: samba-ad
spec:
  selector:
    kubevirt.io/domain: samba-ad
  ports:
    # LDAP
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP
    # Kerberos (KDC)
    - name: kerberos-tcp
      port: 88
      targetPort: 88
      protocol: TCP
    - name: kerberos-udp
      port: 88
      targetPort: 88
      protocol: UDP
    # kpasswd / kadmind
    - name: kpasswd-tcp
      port: 464
      targetPort: 464
      protocol: TCP
    - name: kpasswd-udp
      port: 464
      targetPort: 464
      protocol: UDP
    # DNS (used by Windows clients in-domain)
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
