[libdefaults]
  default_realm = MATEBANK.DEMO
  dns_lookup_realm = false
  dns_lookup_kdc = false
  rdns = false
  forwardable = true

[realms]
  MATEBANK.DEMO = {
    kdc = samba-ad
    admin_server = samba-ad
  }

[domain_realm]
  .matebank.demo = MATEBANK.DEMO
  matebank.demo = MATEBANK.DEMO
