apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mate-backend
  labels:
    app.kubernetes.io/name: mate-backend
spec:
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: mate-backend:latest
