apiVersion: v1
kind: Secret
metadata:
  name: mate-demo-config
type: Opaque
stringData:
  # Portal client redirect settings (Keycloak realm import)
  MATE_PORTAL_REDIRECT_URIS_JSON: "[\"https://portal.matebank.demo/*\"]"
  MATE_PORTAL_WEB_ORIGINS_JSON: "[\"https://portal.matebank.demo\"]"

  # AD (Samba) LDAP federation settings (Keycloak realm import)
  LDAP_CONNECTION_URL: "ldap://samba-ad:389"
  LDAP_USERS_DN: "CN=Users,DC=matebank,DC=demo"
  LDAP_GROUPS_DN: "CN=Users,DC=matebank,DC=demo"
  LDAP_BIND_DN: "CN=Administrator,CN=Users,DC=matebank,DC=demo"
  LDAP_BIND_CREDENTIAL: "Admin123!"
