apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mate-keycloak
  labels:
    app.kubernetes.io/name: mate-keycloak
spec:
  to:
    kind: Service
    name: mate-keycloak-service
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
