apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../postgres
  - keycloak.yaml
  - keycloak-route.yaml
  - keycloak-config-configmap.yaml
  - keycloak-config-job.yaml
  - keycloak-config-secret.yaml
